apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: fuse-console.v7.6.0
  annotations:
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "false"
    description: The Fuse Console eases the discovery and management of Java applications deployed on OpenShift.
    containerImage: registry.redhat.io/fuse7/fuse-console-operator:1.6
    repository: https://github.com/hawtio/hawtio-operator
    createdAt: "2020-01-09T10:59:00Z"
    support: Red Hat
    alm-examples: |-
      [{
        "apiVersion": "hawt.io/v1alpha1",
        "kind": "Hawtio",
        "metadata": {
          "name": "fuse-console"
        },
        "spec": {
          "replicas": 1,
          "version": "7.6.0"
        }
      }]
  namespace: placeholder
spec:
  displayName: Red Hat Integration - Fuse Console
  maintainers:
  - name: Jon Anstey
    email: janstey@redhat.com
  provider:
    name: Red Hat
  maturity: alpha
  version: 7.6.0
  description: |

    The Fuse Console eases the discovery and management of Java applications deployed on OpenShift.

    To secure the communication between the Fuse Console and the Jolokia agents, a client certificate must be generated and mounted into the Fuse Console pod with a secret, to be used for TLS client authentication. This client certificate must be signed using the [service signing certificate](https://docs.openshift.com/container-platform/4.2/authentication/certificates/service-serving-certificate.html) authority private key.

    Here are the steps to be performed prior to the deployment:

    1. First, retrieve the service signing certificate authority keys, by executing the following commmands as a _cluster-admin_ user:
        ```sh
        # The CA certificate
        $ oc get secrets/signing-key -n openshift-service-ca -o "jsonpath={.data['tls\.crt']}" | base64 --decode > ca.crt
        # The CA private key
        $ oc get secrets/signing-key -n openshift-service-ca -o "jsonpath={.data['tls\.key']}" | base64 --decode > ca.key
        ```

    2. Then, generate the client certificate, as documented in [Kubernetes certificates administration](https://kubernetes.io/docs/concepts/cluster-administration/certificates/), using either `easyrsa`, `openssl`, or `cfssl`, e.g., using `openssl`:
        ```sh
        # Generate the private key
        $ openssl genrsa -out server.key 2048
        # Write the CSR config file
        $ cat <<EOT >> csr.conf
        [ req ]
        default_bits = 2048
        prompt = no
        default_md = sha256
        distinguished_name = dn

        [ dn ]
        CN = hawtio-online.hawtio.svc

        [ v3_ext ]
        authorityKeyIdentifier=keyid,issuer:always
        keyUsage=keyEncipherment,dataEncipherment,digitalSignature
        extendedKeyUsage=serverAuth,clientAuth
        EOT
        # Generate the CSR
        $ openssl req -new -key server.key -out server.csr -config csr.conf
        # Issue the signed certificate
        $ openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 10000 -extensions v3_ext -extfile csr.conf
        ```

    3. Finally, you can create the secret to be mounted in the Fuse Console pod, from the generated certificate:
       ```sh
       $ oc create secret tls fuse-console-tls-proxying --cert server.crt --key server.key
       ```

    Note that `CN=fuse-console.fuse.svc` must be trusted by the Jolokia agents, for which client certification authentication is enabled. See the `clientPrincipal` parameter from the [Jolokia agent configuration options](https://jolokia.org/reference/html/agents.html#agent-jvm-config).
  keywords:
  - Fuse
  - Hawtio
  - Java
  - Management
  - Console
  links:
    - name: Red Hat Fuse Console Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_fuse/7.5/html/managing_fuse
    - name: Upstream Hawtio Web site
      url: https://hawt.io
    - name: Upstream Hawtio operator
      url: https://github.com/hawtio/hawtio-operator
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMDt9LmNscy0ye2ZpbGw6I2MyMWEwMDt9LmNscy0ze2ZpbGw6I2ZmZjt9LmNscy00e2ZpbGw6I2VhZWFlYTt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPnByb2R1Y3RpY29uc18xMDE3X1JHQl9JbnRlZ3JhdGlvbiBmaW5hbCBjb2xvcjwvdGl0bGU+PGcgaWQ9IkxheWVyXzEiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PGNpcmNsZSBjbGFzcz0iY2xzLTEiIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTIwLjcxIDUwKSByb3RhdGUoLTQ1KSIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTg1LjM2LDE0LjY0QTUwLDUwLDAsMCwxLDE0LjY0LDg1LjM2WiIvPjxwYXRoIGQ9Ik0zMSwzMS4zNmExLjk0LDEuOTQsMCwwLDEtMy42Mi0uODkuNDMuNDMsMCwwLDEsLjUzLS40NCwzLjMyLDMuMzIsMCwwLDAsMi44MS43QS40My40MywwLDAsMSwzMSwzMS4zNloiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik03Ny42Myw0NC43NkM3Ny4xMiw0MS4zNCw3MywyMSw2Ni4zMiwyMWMtMi40NCwwLTQuNTksMy4zNS02LDYuODgtLjQ0LDEuMDYtMS4yMywxLjA4LTEuNjMsMEM1Ny4yNCwyNC4xNiw1NS44OCwyMSw1My4yOCwyMSw0My4zNCwyMSw0Ny44NCw0NS4xOCwzOSw0NS4xOGMtNC41NywwLTUuMzctMTAuNTktNS41LTE0LjcyLDIuMTkuNjUsMy4zLTEsMy41NS0yLjYxYS42My42MywwLDAsMC0uNDgtLjcyLDMuMzYsMy4zNiwwLDAsMC0zLC44OUgyNy4zMWExLDEsMCwwLDAtLjY4LjI4bC0uNTMuNTNIMjIuMjFhLjU0LjU0LDAsMCwwLS4zOC4xNmwtMy45NSwzLjk1YS41NC41NCwwLDAsMCwuMzguOTFoLjM2bDAsMEgyOS43MWMuNiw2LjI2LDEuNzUsMjIsMTYuNDIsMTcuMTlsLS4zMiw1TDQ0LjM3LDc4LjQ2YTEsMSwwLDAsMCwxLDFoNC45YTEsMSwwLDAsMCwxLTFsLS42MS0yMy4zMy0uMTUtNS44MWM2LTIuNzgsOS01LjY2LDE2LjE5LTYuNzUtMS41OSwyLjYyLTIuMDUsNi44Ny0yLjA2LDgtLjA2LDYsMi41NSw4Ljc0LDUsMTMuMjJMNjMuNzMsNzhhMSwxLDAsMCwwLC44OSwxLjMyaDQuNjRhMSwxLDAsMCwwLC45My0uNzRMNzQsNjIuNmMtNC44My03LjQzLDEuODMtMTUuMzEsMy40MS0xN0ExLDEsMCwwLDAsNzcuNjMsNDQuNzZaTTMxLDMxLjM2YTEuOTQsMS45NCwwLDAsMS0zLjYyLS44OS40My40MywwLDAsMSwuNTMtLjQ0LDMuMzIsMy4zMiwwLDAsMCwyLjgxLjdBLjQzLjQzLDAsMCwxLDMxLDMxLjM2WiIvPjxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTTQ2LjEzLDUxLjA3QzMxLjQ2LDU1LjkyLDMwLjMxLDQwLjE0LDI5LjcxLDMzLjg4SDE4LjY1TDIwLjc1LDM2YTEsMSwwLDAsMCwuNjguMjhoNmMwLDUuOCwxLjEzLDIwLjIsMTQsMjAuMmEzMS4zNCwzMS4zNCwwLDAsMCw0LjQyLS4zNVoiLz48cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Ik01MC40MSw0OS4zNmwuMTUsNS44MWExMDguMiwxMDguMiwwLDAsMCwxNC00LjU0LDE5Ljc5LDE5Ljc5LDAsMCwxLDIuMDYtOEM1OS40Niw0My43LDU2LjQ0LDQ2LjU4LDUwLjQxLDQ5LjM2WiIvPjwvZz48L3N2Zz4=
    mediatype: image/svg+xml
  customresourcedefinitions:
    owned:
    - name: hawtios.hawt.io
      displayName: Hawtio
      description: A Fuse Console
      kind: Hawtio
      version: v1alpha1
      specDescriptors:
        - description: The number of Fuse console pods to deploy
          displayName: Replicas
          path: replicas
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:Deployment'
            - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        - description: The version used for the Fuse console
          displayName: Version
          path: version
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:Deployment'
            - 'urn:alm:descriptor:com.tectonic.ui:text'
  install:
    spec:
      deployments:
      - name: fuse-console-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: fuse-console-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: fuse-console-operator
            spec:
              containers:
              - command:
                - hawtio-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: fuse-console-operator
                image: registry.redhat.io/fuse7/fuse-console-operator:1.6
                imagePullPolicy: Always
                name: fuse-console-operator
                ports:
                - containerPort: 60000
                  name: metrics
                resources: {}
              serviceAccountName: fuse-console-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - serviceaccounts
          - services
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes/custom-host
          verbs:
          - create
        - apiGroups:
          - template.openshift.io
          resources:
          - processedtemplates
          verbs:
          - '*'
        - apiGroups:
          - hawt.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: fuse-console-operator
      clusterPermissions:
      - rules:
        - apiGroups:
          - oauth.openshift.io
          resources:
          - oauthclients
          verbs:
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions
          verbs:
          - get
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - console.openshift.io
          resources:
          - consolelinks
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: fuse-console-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces